export const GET_DATA = 'GET_DATA'
export const GET_DATA_SUCCESSFUL = 'GET_DATA_SUCCESSFUL'

export const ADD_DATA = 'ADD_DATA'
export const ADD_DATA_SUCCESSFULL = 'ADD_DATA_SUCCESSFULL'

export const UPDATE_DATA = 'UPDATE_DATA'
export const UPDATE_DATA_SUCCESSFULL = 'UPDATE_DATA_SUCCESSFULL'

export const TRIGGER_MODAL = 'TRIGGER_MODAL'

export const EDIT_DATA = 'EDIT_DATA'

export const DELETE_DATA = 'DELETE_DATA'