export const GET_DATA = 'GET_DATA'
export const GET_DATA_SUCCESSFUL = 'GET_DATA_SUCCESSFUL'

export const ADD_DATA = 'ADD_DATA'
export const ADD_DATA_SUCCESSFULL = 'ADD_DATA_SUCCESSFULL'

export const TRIGGER_MODAL = 'TRIGGER_MODAL'