# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cookBook' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cookBook
  pod 'Firebase/Core'
  pod 'Firebase/Database', '~> 6.3.0'

end
